### ISSUE TITLE
ModuleNotFoundError: No module named 'web'

### ISSUE THREAD

**Issue by lgs777** [konstantgr/smatched#5]
**poetry run streamlit run web/app.py 
  When you run it, you'll see an error like the one below. How can we fix it? I really need this technology.**

You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.120:8501

2024-01-31 02:12:29.072 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\hackathon-makeup-OA93oZWb-py3.10\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\AI\Smatched\web\app.py", line 3, in <module>
    from web import MAIN_FOLDER
ModuleNotFoundError: No module named 'web'
2024-01-31 02:12:30.041 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\hackathon-makeup-OA93oZWb-py3.10\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\AI\Smatched\web\app.py", line 3, in <module>
    from web import MAIN_FOLDER
ModuleNotFoundError: No module named 'web'
2024-01-31 02:12:36.735 Uncaught app excep

**Comment by lgs777** [comment]
poetry shell
poetry install

The problem was caused by running without following the steps above. Solved!

**Comment by konstantgr** [comment]
Thanks a lot for your feedback! It's good to know that your issue was solved!
